/**
 * Markdown, for a pull request comment or a job summary.
 *
 * The audience is a reviewer who did not run the tool and is looking at a
 * workflow change. Findings lead with the consequence; the rule id and the
 * evidence sit behind a `<details>`, because the first question is "does this
 * matter" and only the second is "why does it say that".
 */

import type { Finding, ScanReport, Severity } from '../types.ts';

const SEVERITY_BADGE: Readonly<Record<Severity, string>> = {
  critical: '🔴 critical',
  high: '🟠 high',
  medium: '🟡 medium',
  low: '🔵 low',
  info: '⚪ info',
};

export interface MarkdownOptions {
  readonly warnings?: readonly string[];
  readonly title?: string;
}

export function renderMarkdown(report: ScanReport, options: MarkdownOptions = {}): string {
  const title = options.title ?? 'Agent workflow review';
  const lines: string[] = [];

  if (title !== '') lines.push(`## ${title}`, '');

  const { summary } = report;
  lines.push(
    `\`${summary.workflows}\` workflows · \`${summary.jobs}\` jobs · ` +
      `\`${summary.agentJobs}\` run an AI agent · \`${summary.findings}\` findings`,
    '',
  );

  for (const warning of options.warnings ?? []) lines.push('> [!WARNING]', `> ${warning}`, '');

  if (summary.agentJobs === 0) {
    lines.push(
      'No AI agent steps found. There is nothing here for this tool to analyse — general workflow security is `zizmor` and `actionlint` territory.',
      '',
    );
    return lines.join('\n');
  }

  const findings = report.workflows.flatMap((workflow) => workflow.findings);

  if (findings.length === 0) {
    lines.push('No findings. Every agent job is reachable only by trusted input, or holds nothing worth taking.', '');
  }

  const blocking = findings.filter((finding) => finding.severity === 'critical' || finding.severity === 'high');
  const rest = findings.filter((finding) => finding.severity !== 'critical' && finding.severity !== 'high');

  if (blocking.length > 0) {
    lines.push('### Worth stopping for', '');
    for (const finding of blocking) lines.push(...renderFinding(finding));
  }

  if (rest.length > 0) {
    lines.push('<details>', `<summary>Also found (${rest.length})</summary>`, '');
    lines.push('| Severity | Rule | Where | What |', '| --- | --- | --- | --- |');
    for (const finding of rest) {
      lines.push(
        `| ${SEVERITY_BADGE[finding.severity]} | \`${finding.ruleId}\` | \`${finding.workflow}:${finding.line}\` | ${escapeCell(finding.message)} |`,
      );
    }
    lines.push('', '</details>', '');
  }

  const unanalysable = report.workflows.filter((workflow) => workflow.unanalysable);
  if (unanalysable.length > 0) {
    lines.push('> [!IMPORTANT]', '> These workflows could not be parsed and were **not** analysed:', '>');
    for (const workflow of unanalysable) lines.push(`> - \`${workflow.path}\``);
    lines.push('');
  }

  lines.push(
    `<sub>Generated by [${report.tool.name}](https://github.com/hamodywe/promptfence) v${report.tool.version}. ` +
      'Static analysis — it reports reachable paths, not exploits.</sub>',
    '',
  );

  return lines.join('\n');
}

function renderFinding(finding: Finding): string[] {
  const lines: string[] = [
    `#### ${SEVERITY_BADGE[finding.severity]} \`${finding.workflow}:${finding.line}\``,
    '',
    finding.message,
    '',
    `**So:** ${finding.consequence}`,
    '',
    `**Fix:** ${finding.remediation}`,
    '',
    '<details>',
    `<summary>Evidence — <code>${finding.ruleId}</code></summary>`,
    '',
  ];

  for (const evidence of finding.evidence) {
    const where = evidence.line !== undefined ? ` *(line ${evidence.line})*` : '';
    lines.push(`- **${evidence.label}** — ${escapeCell(evidence.detail)}${where}`);
  }

  lines.push('', '</details>', '');
  return lines;
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
